apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: capacitacion
  name: capacitacion
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: capacitacion
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capacitacion
    spec:
      containers:
      - env:
        image: aproddevopsrc.azurecr.io/imagekeyword
        imagePullPolicy: Always
        name: capacitacion
        ports:
        - containerPort: 3000
          name: 3000tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capacitacion
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - capacitacion-desa.telefonicawebsites.co
      secretName: ingress-tls-csi
  rules:
    - host: capacitacion-desa.telefonicawebsites.co
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: service-capacitacion
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: capacitacion
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ExternalName
  sessionAffinity: None
  #externalName: referidosfront.referidos-whatsapp.svc.cluster.local

